spring.application.name=sistema
# Conexion a la base de de restaurante
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/restaurantebd
spring.datasource.username=root
spring.datasource.password=Ctellez27

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

spring.jpa.hibernate.ddl-auto=update

